language: java
jdk:
  - oraclejdk7
  - openjdk7
branches:
  only:
    - master
    - 3
    - 3.5
before_install:
  - 'mvn -version'
  - sudo apt-get -qq update
  - sudo apt-get install zookeeper
install: 'mvn clean install -Dmaven.test.skip=true --also-make-dependents'